### ISSUE TITLE
最新版本的 bpmn-js 英文有变动

### ISSUE THREAD

**Issue by ilii** [miyuesc/bpmn-js-i18n-zh#1]
最新版本的 bpmn-js 有很多单词修改成大写了。这样很多都匹配不到。例如：Start Event

**Comment by miyuesc** [comment]
> 最新版本的 bpmn-js 有很多单词修改成大写了。这样很多都匹配不到。例如：Start Event

后面我看看吧

**Comment by ilii** [comment]
已收到邮件

**Comment by miyuesc** [comment]
我看了一下，基本上都是能对上的呀，你用的哪个版本呢？是 bpmn-js 还是 properties-panel 的对应有问题？

**Comment by ilii** [comment]
所有两个单词的，官方都改成首写字母大写了。我看了官方的多语言也是有问题的。看来太新了
"bpmn-js": "^17.9.2"
"bpmn-js-properties-panel": "^5.23.0"
我写的demo用的都是最新版本
![图片](https://github.com/user-attachments/assets/7ac6a71d-a727-44c3-82a1-b45e803be3a8)

**Comment by miyuesc** [comment]
> 所有两个单词的，官方都改成首写字母大写了。我看了官方的多语言也是有问题的。看来太新了 "bpmn-js": "^17.9.2" "bpmn-js-properties-panel": "^5.23.0" 我写的demo用的都是最新版本 ![图片](https://private-user-images.githubusercontent.com/1763213/364609300-7ac6a71d-a727-44c3-82a1-b45e803be3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MDU4NzMsIm5iZiI6MTcyNTUwNTU3MywicGF0aCI6Ii8xNzYzMjEzLzM2NDYwOTMwMC03YWM2YTcxZC1hNzI3LTQ0YzMtODJhMS1iNDVlODAzYmUzYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMDMwNjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZmMzcxNDI3MmFhNWM4YWYyOGMzM2I4MWVhYmRiMDg1Yzk5M2ZiY2JiODMyZjg4MTE5MzY1NzZkZWE4YTI3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NsfNsDwh6g3FWUx2Q-ypj0mzBeK91E4Imi2l8QbDS3A)

Properties panel 的我最近没怎么注意。大部分时候都是推荐自己开发一个属性面板的。

抽空我会看一下这个问题

**Comment by miyuesc** [comment]
> Start Event

@ilii 我看了一下 bpmn-js-properties-panel 的代码，目前应该不是语言匹配的问题，而且 header 部分的元素类型并没有做国际化适配。
